# Form implementation generated from reading ui file 'UI\mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1381, 675)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 49, 1291, 531))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.succesTable = QtWidgets.QTableView(self.gridLayoutWidget)
        self.succesTable.setObjectName("succesTable")
        self.gridLayout.addWidget(self.succesTable, 0, 0, 1, 1)
        self.chooseFileBtn = QtWidgets.QPushButton(self.centralwidget)
        self.chooseFileBtn.setGeometry(QtCore.QRect(10, 10, 80, 27))
        self.chooseFileBtn.setObjectName("chooseFileBtn")
        self.exportFileBtn = QtWidgets.QPushButton(self.centralwidget)
        self.exportFileBtn.setGeometry(QtCore.QRect(670, 10, 80, 27))
        self.exportFileBtn.setObjectName("exportFileBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1381, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.chooseFileBtn.setText(_translate("MainWindow", "Choose file"))
        self.exportFileBtn.setText(_translate("MainWindow", "Export file"))
